import { jsPDF } from 'jspdf';

/**
 * Generates a professional MLX NORM approval certificate as a downloadable PDF.
 */
export const generateCertificatePDF = (application) => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // ──── Background ────
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, W, H, 'F');

  // Outer border (double line)
  doc.setDrawColor(22, 163, 74); // green-600
  doc.setLineWidth(2);
  doc.rect(8, 8, W - 16, H - 16);
  doc.setLineWidth(0.5);
  doc.rect(12, 12, W - 24, H - 24);

  // Corner ornaments (small squares)
  const cornerSize = 6;
  doc.setFillColor(22, 163, 74);
  [[12, 12], [W - 12 - cornerSize, 12], [12, H - 12 - cornerSize], [W - 12 - cornerSize, H - 12 - cornerSize]].forEach(([x, y]) => {
    doc.rect(x, y, cornerSize, cornerSize, 'F');
  });

  // ──── Header Section ────
  let y = 35;

  // Title
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(22, 163, 74);
  doc.text('MLX NORM REGISTRATION AUTHORITY', W / 2, y, { align: 'center' });
  y += 12;

  doc.setFontSize(28);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text('CERTIFICATE OF APPROVAL', W / 2, y, { align: 'center' });
  y += 10;

  // Decorative line under title
  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(1);
  doc.line(W / 2 - 50, y, W / 2 + 50, y);
  y += 6;
  doc.setLineWidth(0.3);
  doc.line(W / 2 - 35, y, W / 2 + 35, y);
  y += 12;

  // ──── Body Text ────
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text('This is to certify that the article registration application submitted by', W / 2, y, { align: 'center' });
  y += 12;

  // Applicant Name
  const applicantName = application.user?.name || application.ownerDetails?.name || 'Applicant';
  doc.setFontSize(22);
  doc.setTextColor(22, 163, 74);
  doc.text(applicantName, W / 2, y, { align: 'center' });
  y += 8;

  // Underline under name
  const nameWidth = doc.getTextWidth(applicantName);
  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(0.5);
  doc.line(W / 2 - nameWidth / 2, y, W / 2 + nameWidth / 2, y);
  y += 12;

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('has been reviewed and approved by the administrative authority.', W / 2, y, { align: 'center' });
  y += 16;

  // ──── Details Grid ────
  doc.setFontSize(9);
  const leftCol = W / 2 - 70;
  const rightCol = W / 2 + 10;
  const lineH = 8;

  const details = [
    ['Registration Number', application.registrationNumber || 'N/A'],
    ['Application ID', application._id || 'N/A'],
    ['Article Shape', application.articleDescription?.shape || 'N/A'],
    ['Article Weight', application.articleDescription?.weight || 'N/A'],
    ['Origin', application.articleDescription?.origin || 'N/A'],
    ['Authority Type', application.workingAuthority?.authorityType || 'N/A'],
  ];

  // Draw details in 2 columns
  for (let i = 0; i < details.length; i++) {
    const col = i < 3 ? leftCol : rightCol;
    const row = i < 3 ? i : i - 3;
    const yPos = y + row * lineH;

    doc.setTextColor(100, 116, 139);
    doc.text(details[i][0] + ':', col, yPos);
    doc.setTextColor(30, 41, 59);
    doc.text(details[i][1], col + 45, yPos);
  }

  y += 3 * lineH + 10;

  // ──── Approval Date ────
  const approvalDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.3);
  doc.line(20, y, W - 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Date of Approval: ${approvalDate}`, W / 2, y, { align: 'center' });
  y += 16;

  // ──── Signature Lines ────
  const sigY = y;
  doc.setDrawColor(148, 163, 184); // slate-400
  doc.setLineWidth(0.3);

  // Left signature
  doc.line(40, sigY, 110, sigY);
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Authorized Signatory', 75, sigY + 5, { align: 'center' });

  // Right signature
  doc.line(W - 110, sigY, W - 40, sigY);
  doc.text('Administrative Officer', W - 75, sigY + 5, { align: 'center' });

  // ──── Footer ────
  doc.setFontSize(7);
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(
    'This certificate is digitally generated by MLX NORM Registration Portal. Verify authenticity at mlxnorm.gov.in',
    W / 2, H - 16, { align: 'center' }
  );

  // ──── Save ────
  const fileName = `MLX_NORM_Certificate_${application.registrationNumber || application._id}.pdf`;
  doc.save(fileName);
};
